cloud:
  aws:
    credentials:
      access-key: AKIAXLQ5RTOCKHO45WAE
      secret-key: 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
    region:
      static: eu-west-2
    stack:
      auto: false

application:
  bucket:
    name: s3-test-without-signed-url


spring:
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2MB
      max-file-size: 5MB
      max-request-size: 10MB

